name: Terraform Provision

on:
  push:
    branches: [ TestingBranch ]
  pull_request:
    branches: [ TestingBranch ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Terraform Init
      run: terraform init
      working-directory: Terraform

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: Terraform

    - name: Save EC2 IP
      run: terraform output -raw NginxAWS_server_public_ip > ec2_ip.txt
      working-directory: Terraform

    - name: Upload EC2 IP artifact
      uses: actions/upload-artifact@v3
      with:
        name: ec2-ip
        path: Terraform/ec2_ip.txt
