# .github/workflows/terraform.yml
name: Terraform CI/CD

on:
  push:
    branches: [ TestingBranch ]
  pull_request:
    branches: [ TestingBranch ]

jobs:
  terraform:
    name: Provision Infrastructure
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Terraform 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        terraform apply -auto-approve
        terraform output -json > tf_output.json

    - name: Save EC2 IP
      id: save_ip
      run: |
        IP=$(jq -r .ec2_public_ip.value tfoutput.json)
        echo "EC2_IP=$IP" >> $GITHUB_ENV

    - name: Install Ansible
      run: sudo apt-get update && sudo apt-get install -y ansible

    - name: Generate Inventory 
      run: |
        echo "[ephemeral]" > inventory.ini
        echo "$EC2_IP ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa" >> inventory.ini

    - name: Run Ansible Playbook
      uses: dawidd6/action-ansible-playbook@v2
      with:
        playbook: deploy.yml
        inventory: |
          [web]
          ${{env.EC2_IP}}
      env:
        DOCKER_TAG: ${{ENV.DOCKER_TAG}}

